# Generated by Django 6.0.6 on 2026-06-10 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon_class', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Project Categories',
            },
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('icon_class', models.CharField(blank=True, max_length=100)),
                ('color', models.CharField(default='#00D9FF', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Technologies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('project_type', models.CharField(choices=[('data', 'Data Analytics'), ('product', 'Product Management'), ('dashboard', 'Dashboard'), ('automation', 'Automation'), ('research', 'Research'), ('web', 'Web Application'), ('other', 'Other')], default='data', max_length=20)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('in_progress', 'In Progress'), ('planned', 'Planned'), ('archived', 'Archived')], default='completed', max_length=20)),
                ('short_description', models.TextField(max_length=500)),
                ('overview', models.TextField(blank=True)),
                ('problem_statement', models.TextField(blank=True)),
                ('objectives', models.TextField(blank=True)),
                ('requirements', models.TextField(blank=True)),
                ('architecture', models.TextField(blank=True)),
                ('database_design', models.TextField(blank=True)),
                ('features', models.TextField(blank=True)),
                ('challenges', models.TextField(blank=True)),
                ('solutions', models.TextField(blank=True)),
                ('lessons_learned', models.TextField(blank=True)),
                ('future_improvements', models.TextField(blank=True)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('demo_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('documentation_url', models.URLField(blank=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='projects.projectcategory')),
                ('technologies', models.ManyToManyField(blank=True, to='projects.technology')),
            ],
            options={
                'ordering': ['-is_featured', 'order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/gallery/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_screenshot', models.BooleanField(default=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='projects.project')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProjectMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
                ('icon_class', models.CharField(blank=True, max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='projects.project')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
