# Generated by Django 6.0.6 on 2026-06-10 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('issuing_org', models.CharField(max_length=200)),
                ('issue_date', models.DateField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('credential_id', models.CharField(blank=True, max_length=200)),
                ('credential_url', models.URLField(blank=True)),
                ('badge_image', models.ImageField(blank=True, null=True, upload_to='certifications/')),
                ('is_featured', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=200)),
                ('degree', models.CharField(max_length=200)),
                ('field_of_study', models.CharField(max_length=200)),
                ('start_year', models.PositiveIntegerField()),
                ('end_year', models.PositiveIntegerField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('gpa', models.CharField(blank=True, max_length=10)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-start_year'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('technologies', models.CharField(blank=True, max_length=500)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Peter Charles Portfolio', max_length=100)),
                ('tagline', models.CharField(default='Data Analyst & Product Manager', max_length=255)),
                ('about_short', models.TextField(blank=True)),
                ('about_full', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('location', models.CharField(blank=True, default='Abuja, Nigeria', max_length=100)),
                ('linkedin_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('resume_file', models.FileField(blank=True, null=True, upload_to='resume/')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('years_experience', models.PositiveIntegerField(default=5)),
                ('projects_completed', models.PositiveIntegerField(default=30)),
                ('clients_served', models.PositiveIntegerField(default=20)),
                ('certifications_count', models.PositiveIntegerField(default=10)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('data', 'Data Analytics'), ('product', 'Product Management'), ('tech', 'Technical Skills'), ('soft', 'Soft Skills'), ('tools', 'Tools & Platforms')], max_length=20)),
                ('proficiency', models.PositiveIntegerField(default=80, help_text='0-100')),
                ('icon_class', models.CharField(blank=True, help_text='FontAwesome or Devicon class', max_length=100)),
                ('color', models.CharField(default='#00D9FF', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
    ]
