# Generated by Django 6.0.6 on 2026-06-11 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='students_trained',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='experience',
            name='technologies',
            field=models.CharField(blank=True, help_text='Comma-separated list of technologies', max_length=500),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='tagline',
            field=models.CharField(default='Cybersecurity Engineer & Django Developer', max_length=255),
        ),
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('cybersecurity', 'Cybersecurity'), ('python', 'Python Development'), ('django', 'Django & Web'), ('osint', 'OSINT & Recon'), ('tools', 'Tools & Platforms'), ('soft', 'Soft Skills')], max_length=20),
        ),
    ]
