# Generated by Django 6.0.6 on 2026-06-10 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=15)),
                ('delivery_mode', models.CharField(choices=[('online', 'Online'), ('in_person', 'In-Person'), ('hybrid', 'Hybrid')], default='online', max_length=15)),
                ('short_description', models.TextField(max_length=300)),
                ('full_description', models.TextField(blank=True)),
                ('curriculum', models.TextField(blank=True, help_text='Markdown or HTML')),
                ('duration_weeks', models.PositiveIntegerField(default=4)),
                ('hours_per_week', models.PositiveIntegerField(default=5)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_participants', models.PositiveIntegerField(default=20)),
                ('prerequisites', models.TextField(blank=True)),
                ('tools_used', models.CharField(blank=True, max_length=500)),
                ('certificate_offered', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('icon_class', models.CharField(default='fas fa-graduation-cap', max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
    ]
